<script>
    new Ext.Viewport({
        layout: 'border',
        items:[{
                id:'qform_north',
                region:'north',
                height:100,
                bbar:['->',{
                   text:'{_LOGOUT}: <?php echo $this->user->name;?>',
                   handler: function(){document.location.href='qform/logout'}
                }]
            },{
                id:'qform_west',
                region:'west',
                width:200,
                split:true
            },{
                id:'qform_center',
                region:'center',
                layout:'fit',
                items:[{
                 xtype: qf.load.xtype('logo'),
                 border:false,
                 text:'<?php echo $this->config->title; ?>'
                }]
            },{
                id:'qform_east',
                region:'east',
                hiddent:true
            },{
                region:'south',
                height:50,
                minHeight:50,
                logoHeight:30,
                xtype: qf.load.xtype('logo'),
                border:true,
                text:'<?php echo $this->config->title; ?>'
            }] 
    });
</script>