<script>
    new Ext.Viewport({
        layout: 'border',
        items:[{
                id:'qform_north',
                region:'north',
                height:100,
                bbar:['->',{
                   iconCls:qf.load.icon('key--arrow'),
                   tiptool:'{_LOGOUT}',
                   text:'<?php echo $this->user->name;?>',
                   handler: function(){document.location.href='qform/logout'}
                }]
            },{
                id:'qform_west',
                region:'west',
                width:200,
                split:true,
                layout:'fit',
                xtype: qf.load.xtype('qfmenu'),
                iconCls: qf.load.icon('ui-menu')
            },{
                id:'qform_center', //important id!
                region:'center',
                xtype:'tabpanel',
                activeTab:0,
                autoDestroy:true,
                items:[{
                title:'{_CP_NAME}',
                xtype: qf.load.xtype('logo'),
                iconCls: qf.load.icon('information-frame'),
                border:false
                }]
            },{
                id:'qform_east',
                region:'east',
                hiddent:true
            },{
                region:'south',
                height:50,
                minHeight:50,
                logoHeight:30,
                xtype: qf.load.xtype('logo'),
                border:true,
                text:'<?php echo $this->config->title; ?>'
            }] 
    });
</script>