<script>
var login = function(){
    var form = this.ownerCt.ownerCt;
    if(form.getForm().isValid()){
        form.getForm().submit({
          url:'loginSubmit',
          success:function(f,r){
              if(r.result.success)
               document.location.href = '/qform';
          },
          failure:function(f,r){
              Ext.Msg.alert('{_WARNING}',r.result.msg,function(){
                  form.get(1).focus().selectText();
              });
              
          }
        });
    }
}
new Ext.Viewport({
    layout: 'border',
    items:[{
       region:'north',
       height:100     
    },{
        region:'west',
        width:250,
        title:'{_MENU}',
        iconCls:qf.load.icon('ui-menu'),
        layout:'vbox',
        layoutConfig:{
           align:'stretch',
           pack:'end'
        },
        items:[{
           title:'{_LOGIN}',
           xtype:'form',
           height:130,
           border:false,
           layout:'form',
           iconCls: qf.load.icon('key-solid'),
           padding:5,
           items:[{
              fieldLabel:'{_USERNAME}',
              xtype:'textfield',
              anchor:'0',
              allowBlank:false,
              name:'username',
              value:'Admin'
           },{
              fieldLabel:'{_PASSWORD}',
              xtype:'textfield',
              anchor:'0',
              inputType:'password',
              allowBlank:false,
              name:'password',
              value:'dupa',
              enableKeyEvents:true,
              listeners:{
                  keyup:function(f,e){
                      if(e.keyCode == 13) {
                          var button = this.ownerCt.buttons[1];
                              button.handler.call(button.scope || button, button);
                          //this.ownerCt.buttons().get(1).handler();
                      }
                  }
              }
           }],
           buttons:[{
               text:'{_HOME}',
               iconCls: qf.load.icon('home'),
               handler: function(){document.location.href = '/'}
           },{
               text:'{_LOGIN}',
               iconCls: qf.load.icon('key'),
               handler: login
           }]
        }]
    },{
        region:'center'
    },{
        region:'south',
        height:50,
        bodyStyle:{
          'display':'table-cell',
          'text-align':'center',
          'vertical-align':'middle',
          'font-family':'verdana',
          'color':'#ddd',
          'font-size':'11px'
        },
        html: '<div style="text-align:center;"><div style="border-radius:4px;border:1px solid #ddd;width:150px;margin:auto;"><?php echo $this->config->title; ?></div></div>'
    }]
});

</script>