<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Quick Form - FastEasyApplicationCreator</title>
        <?php echo $this->headLink()->appendStylesheet('/css/global.css');
              echo $this->headScript()->appendFile('/js/jquery.js');
        ?>
    </head>
    <body>
        <?php echo $this->layout()->content ?>
    </body>
</html>